services:
  - type: web
    name: securex
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix securex-main
      npm run build --prefix securex-main
    startCommand: gunicorn app:app